### ISSUE TITLE
Add support for Linux in HTTP client

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-cpp-tracker#5]

**Comment by fire** [comment]
What is needed for Linux support?

**Comment by jbeemster** [comment]
Hi @fire I believe we just need a Linux compatible HTTP Client (https://github.com/snowplow/snowplow-cpp-tracker/blob/master/src/http_client.cpp).  Currently we have a testing base, Win32 and macOS.

Utils also has a bunch of Windows and macOS specifics that would need to be ported. (https://github.com/snowplow/snowplow-cpp-tracker/blob/master/src/utils.cpp)
