### ISSUE TITLE
Want to link static library with my application/lib

### ISSUE THREAD

**Issue by franNadalesDN** [snowplow/snowplow-cpp-tracker#85]
**Is your feature request related to a problem? Please describe.**
I want to link snowplow static library with my application code but it seems configuration is fixed by CMakeFiles.txt

I am using FetchContent method.

**Describe the solution you'd like**
I'd like to link with snowplow static lib by using an easy way.

**Describe alternatives you've considered**
I've tryed to link by using snowplow.lib but includes break.  

I also tried to add include paths to headers and libs but it misses nlohmann dependencies.

**Additional context**
I want to have the smaller binaries as possible.

**Comment by matus-tomlein** [comment]
Hi @franNadalesDN, thank you for raising this issue!

We are currently reviewing a contribution in PR #86 that adds the option to build a static library using cmake. If you have the chance, we'd appreciate any further comments or feedback whether this would address your request!

Copying the README section here from the PR:

#### Installation: As an imported target in your CMake project

First, build and install the project. Make sure the project uses the external JSON and SQLite3 libraries (`SNOWPLOW_USE_EXTERNAL_JSON=ON` and `SNOWPLOW_USE_EXTERNAL_SQLITE=ON`). Use `BUILD_SHARED_LIBS=OFF` to build a static library. If you have `SQLite3`, `CURL`, `LibUUID` available as system libraries but you need to use different packages (e.g. from Conan) you need to set `CMAKE_FIND_PACKAGE_PREFER_CONFIG=ON` to prevent linking to the system libraries.

```cmake
cmake [...] -DCMAKE_INSTALL_PREFIX=[...]
    -DSNOWPLOW_USE_EXTERNAL_JSON=ON -DSNOWPLOW_USE_EXTERNAL_SQLITE=ON \
    -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON \
    -DSNOWPLOW_BUILD_TESTS=0 -DSNOWPLOW_BUILD_EXAMPLE=0 -DSNOWPLOW_BUILD_PERFORMANCE=0
```

When you're building a shared library you need to use an external JSON library. For a static library you need both JSON and SQLite3 to be external.

After building and installing the project you can use `find_package` to import it into your `CMakeLists.txt`:

```cmake
find_package(snowplow REQUIRED CONFIG)
...
target_link_libraries(your-target snowplow::snowplow)
```

Make sure your project finds the same dependencies what was visible for Snowplow when you were building and installing it. For example, if you have a both a system and local SQlite3 installation and `CMAKE_FIND_PACKAGE_PREFER_CONFIG` was `ON` for Snowplow but `OFF` for your project, Snowplow will be built with the local SQLite3 while the `find_package(snowplow)` in your project will find the system one.
